name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          elixir-version: 1.10.2

      - name: Install dependencies
        run: mix deps.get

      - name: Run tests
        run: mix test
